#!/usr/bin/env python3
"""Build the posting queue.

Instagram's Content Publishing API has no scheduling of its own - unlike Facebook
Pages there is no scheduled_publish_time, so a post happens the moment the API is
called. This turns the two caption files into one dated queue that the publisher
walks through, and a GitHub Actions cron provides the clock.

Output: state/schedule.json, ordered by publish time.
Existing entries in state/published.json are never re-queued.
"""

import hashlib
import json
import os
from datetime import datetime, timedelta, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKT = timezone(timedelta(hours=5))  # Pakistan has no DST; the offset is fixed.


def load(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        return json.load(f)


def jitter(post_id, spread):
    """Deterministic offset in [-spread, +spread] minutes, seeded by post id.

    Deterministic matters: rebuilding the schedule must not reshuffle times for
    posts that already went out, or the published-state check stops lining up.
    """
    h = hashlib.sha256(post_id.encode()).digest()
    return (int.from_bytes(h[:4], "big") % (spread * 2 + 1)) - spread


def order_interleaved(posts):
    """Round-robin across product groups.

    DK has six near-identical 15W panel images. Posted in filename order they
    would run six days straight and read as a stuck feed, so groups are dealt
    out one at a time, largest group first.
    """
    buckets = {}
    for p in posts:
        buckets.setdefault(p.get("group", "_"), []).append(p)
    queues = sorted(buckets.values(), key=len, reverse=True)
    out = []
    while any(queues):
        for q in queues:
            if q:
                out.append(q.pop(0))
    return out


def build():
    cfg = load("config/brands.json")
    start = datetime.strptime(cfg["start_date"], "%Y-%m-%d").replace(tzinfo=PKT)
    spread = cfg.get("jitter_minutes", 0)

    published = set()
    pub_path = os.path.join(ROOT, "state", "published.json")
    if os.path.exists(pub_path):
        with open(pub_path, encoding="utf-8") as f:
            published = {e["id"] for e in json.load(f).get("posts", [])}

    entries, report = [], []

    for key, brand in cfg["brands"].items():
        doc = load(brand["captions"])
        posts = [p for p in doc["posts"] if p.get("publish", True) and p.get("media")]

        if brand.get("order") == "interleave":
            posts = order_interleaved(posts)
        else:
            posts = sorted(posts, key=lambda p: p.get("post_no", 0))

        slots = brand["slots"]
        pins = brand.get("pins", {})

        # Pull pinned posts out of the rolling sequence and place them by date.
        pinned, rolling = [], []
        for p in posts:
            pin = pins.get(str(p.get("post_no")))
            if pin:
                pinned.append((p, pin))
            else:
                rolling.append(p)

        taken = set()
        for p, pin in pinned:
            d = datetime.strptime(pin["date"], "%Y-%m-%d").replace(tzinfo=PKT)
            hh, mm = map(int, pin["slot"].split(":"))
            when = d.replace(hour=hh, minute=mm) + timedelta(minutes=jitter(p["id"], spread))
            taken.add((pin["date"], pin["slot"]))
            entries.append(make(key, brand, p, when, pinned=pin["reason"]))

        # Deal the rest into consecutive day/slot positions, skipping any a pin
        # already occupies so two posts never collide on one slot.
        i = 0
        for p in rolling:
            while True:
                day = start + timedelta(days=i // len(slots))
                slot = slots[i % len(slots)]
                i += 1
                if (day.strftime("%Y-%m-%d"), slot) not in taken:
                    break
            hh, mm = map(int, slot.split(":"))
            when = day.replace(hour=hh, minute=mm) + timedelta(minutes=jitter(p["id"], spread))
            entries.append(make(key, brand, p, when))

        days = (len(posts) + len(slots) - 1) // len(slots)
        last = max(e["publish_at_pkt"] for e in entries if e["brand"] == key)
        report.append((brand["name"], len(posts), len(slots), days, last))

    entries.sort(key=lambda e: e["publish_at_utc"])
    for e in entries:
        e["status"] = "published" if e["id"] in published else "pending"

    out = {
        "generated_note": "Generated by scripts/build_schedule.py - edit config/brands.json "
                          "or the caption files and rebuild, never hand-edit this file.",
        "timezone": cfg["timezone"],
        "posts": entries,
    }
    path = os.path.join(ROOT, "state", "schedule.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")

    for name, n, slots, days, last in report:
        print(f"{name:<14} {n:>3} posts  {slots}/day  ->  {days:>2} days, last on {last[:10]}")
    print(f"\n{len(entries)} queued -> state/schedule.json")
    print("\nFirst week:")
    for e in entries[:14]:
        pin = "  [PINNED]" if e.get("pinned_reason") else ""
        print(f"  {e['publish_at_pkt']}  {e['brand']:<11} {e['id']:<7} {e['product'][:44]}{pin}")


def make(key, brand, p, when, pinned=None):
    e = {
        "id": p["id"],
        "brand": key,
        "brand_name": brand["name"],
        "handle": brand["handle"],
        "media_type": brand["media_type"],
        "media": p["media"],
        "product": p.get("product", ""),
        "caption": p["caption"],
        "hashtags": p.get("hashtags", []),
        "publish_at_pkt": when.strftime("%Y-%m-%d %H:%M"),
        "publish_at_utc": when.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    if pinned:
        e["pinned_reason"] = pinned
    return e


if __name__ == "__main__":
    build()
